-- MySQL Script generated by MySQL Workbench
-- Wed Jul  6 08:43:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev` DEFAULT CHARACTER SET utf8 ;
USE `dev` ;

-- -----------------------------------------------------
-- Table `dev`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`employee` ;

CREATE TABLE IF NOT EXISTS `dev`.`employee` (
  `employee_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(12) NOT NULL,
  `phone` VARCHAR(16) NOT NULL,
  `salesperson_yn` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`customer` ;

CREATE TABLE IF NOT EXISTS `dev`.`customer` (
  `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(16) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `dev`.`employee` (`employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`product_shipper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`product_shipper` ;

CREATE TABLE IF NOT EXISTS `dev`.`product_shipper` (
  `shipper_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shipper_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(16) NOT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `delivery_yn` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  `active_yn` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`shipper_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`order_header`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`order_header` ;

CREATE TABLE IF NOT EXISTS `dev`.`order_header` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT UNSIGNED NOT NULL,
  `shipper_id` INT UNSIGNED NOT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  INDEX `fk_customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_shipper_id_idx` (`shipper_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dev`.`customer` (`customer_id`),
  CONSTRAINT `fk_shipper_id`
    FOREIGN KEY (`shipper_id`)
    REFERENCES `dev`.`product_shipper` (`shipper_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`product_category` ;

CREATE TABLE IF NOT EXISTS `dev`.`product_category` (
  `product_category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(20) NOT NULL,
  `category_description` VARCHAR(200) NOT NULL,
  `use_yn` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`product_category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`product_supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`product_supplier` ;

CREATE TABLE IF NOT EXISTS `dev`.`product_supplier` (
  `supplier_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `contact_name` VARCHAR(10) NOT NULL,
  `contact_phone` VARCHAR(20) NULL DEFAULT NULL,
  `contact_email` VARCHAR(45) NULL DEFAULT NULL,
  `business_no` VARCHAR(45) NULL DEFAULT NULL,
  `representative_name` VARCHAR(10) NULL DEFAULT NULL,
  `created_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`product` ;

CREATE TABLE IF NOT EXISTS `dev`.`product` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_no` VARCHAR(12) NOT NULL,
  `product_name` VARCHAR(100) NOT NULL,
  `product_category_id` INT UNSIGNED NOT NULL,
  `supplier_id` INT UNSIGNED NOT NULL,
  `original_price` INT UNSIGNED NOT NULL,
  `sales_price` INT UNSIGNED NOT NULL,
  `stock` INT UNSIGNED NOT NULL,
  `img1` VARCHAR(100) NULL DEFAULT NULL,
  `img2` VARCHAR(100) NULL DEFAULT NULL,
  `discount_type` ENUM('P', 'F') NULL DEFAULT NULL COMMENT 'P - 퍼센트 할인\\\\nF - 고정금액 할인',
  `discount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_no_UNIQUE` (`product_no` ASC) VISIBLE,
  INDEX `fk_product_category_id_idx` (`product_category_id` ASC) VISIBLE,
  INDEX `fk_supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_id`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `dev`.`product_category` (`product_category_id`),
  CONSTRAINT `fk_supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `dev`.`product_supplier` (`supplier_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `dev`.`order_detail` (
  `order_detail_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `order_qty` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_detail_id`),
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `dev`.`order_header` (`order_id`),
  CONSTRAINT `fk_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `dev`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dev`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev`.`product_image` ;

CREATE TABLE IF NOT EXISTS `dev`.`product_image` (
  `file_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `originalname` VARCHAR(100) NOT NULL,
  `mimetype` VARCHAR(45) NOT NULL,
  `filename` VARCHAR(100) NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_file_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `dev`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
